//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystter_SendTweet.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mystter_SendTweet.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string aboutMenuItem {
            get {
                return ResourceManager.GetString("aboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string accountMenuTitle {
            get {
                return ResourceManager.GetString("accountMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an account.
        /// </summary>
        internal static string addAccountMenuItem {
            get {
                return ResourceManager.GetString("addAccountMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has already added..
        /// </summary>
        internal static string alreadyAdded {
            get {
                return ResourceManager.GetString("alreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now authorizing....
        /// </summary>
        internal static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Append Hashtags.
        /// </summary>
        internal static string AutoAppendHashtags {
            get {
                return ResourceManager.GetString("AutoAppendHashtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string checkForUpdates {
            get {
                return ResourceManager.GetString("checkForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string checkingForUpdates {
            get {
                return ResourceManager.GetString("checkingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Last Tweet.
        /// </summary>
        internal static string deleteBtn {
            get {
                return ResourceManager.GetString("deleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tweet?.
        /// </summary>
        internal static string deleteComfirm {
            get {
                return ResourceManager.GetString("deleteComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete has been cancelled..
        /// </summary>
        internal static string deleteNo {
            get {
                return ResourceManager.GetString("deleteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet has been deleted..
        /// </summary>
        internal static string deleteYes {
            get {
                return ResourceManager.GetString("deleteYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer&apos;s Twitter.
        /// </summary>
        internal static string DeveloperTwitter {
            get {
                return ResourceManager.GetString("DeveloperTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is a duplicate..
        /// </summary>
        internal static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add an account. Please check if your account is valid and try again later..
        /// </summary>
        internal static string FailedToAddAccount {
            get {
                return ResourceManager.GetString("FailedToAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtags.
        /// </summary>
        internal static string Hashtags {
            get {
                return ResourceManager.GetString("Hashtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtags Settings.
        /// </summary>
        internal static string HashtagsSetting {
            get {
                return ResourceManager.GetString("HashtagsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string helpMenuTitle {
            get {
                return ResourceManager.GetString("helpMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version: {version}.
        /// </summary>
        internal static string latestVersionLabel {
            get {
                return ResourceManager.GetString("latestVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the selected account from the list?.
        /// </summary>
        internal static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet is not available..
        /// </summary>
        internal static string networkNotAvailable {
            get {
                return ResourceManager.GetString("networkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth.
        /// </summary>
        internal static string OAuth {
            get {
                return ResourceManager.GetString("OAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are up to date..
        /// </summary>
        internal static string onTheLatestLabel {
            get {
                return ResourceManager.GetString("onTheLatestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings Folder.
        /// </summary>
        internal static string OpenSettingsFolder {
            get {
                return ResourceManager.GetString("OpenSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Repository.
        /// </summary>
        internal static string ProjectRepository {
            get {
                return ResourceManager.GetString("ProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        internal static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string sendBtn {
            get {
                return ResourceManager.GetString("sendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsMenuTitle {
            get {
                return ResourceManager.GetString("settingsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show profile.
        /// </summary>
        internal static string showProfileMenuItem {
            get {
                return ResourceManager.GetString("showProfileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet is too long..
        /// </summary>
        internal static string tooLong {
            get {
                return ResourceManager.GetString("tooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet is too short..
        /// </summary>
        internal static string tooShort {
            get {
                return ResourceManager.GetString("tooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Most.
        /// </summary>
        internal static string topMostMenuItem {
            get {
                return ResourceManager.GetString("topMostMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Exception!.
        /// </summary>
        internal static string TwitterException {
            get {
                return ResourceManager.GetString("TwitterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Exception!.
        /// </summary>
        internal static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates Available!.
        /// </summary>
        internal static string updatesAvailableLabel {
            get {
                return ResourceManager.GetString("updatesAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only upload up to 4 images..
        /// </summary>
        internal static string upTo4Images {
            get {
                return ResourceManager.GetString("upTo4Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This window will be closed shortly....
        /// </summary>
        internal static string WindowClosing {
            get {
                return ResourceManager.GetString("WindowClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        internal static string wordWrapMenuItem {
            get {
                return ResourceManager.GetString("wordWrapMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no account. Please add a twitter account..
        /// </summary>
        internal static string yetAdded1 {
            get {
                return ResourceManager.GetString("yetAdded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will exit if you select No..
        /// </summary>
        internal static string yetAdded2 {
            get {
                return ResourceManager.GetString("yetAdded2", resourceCulture);
            }
        }
    }
}
