//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystter_SendTweet.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mystter_SendTweet.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string aboutMenuItem {
            get {
                return ResourceManager.GetString("aboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string accountMenuTitle {
            get {
                return ResourceManager.GetString("accountMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string addAccountMenuItem {
            get {
                return ResourceManager.GetString("addAccountMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This account has already added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string alreadyAdded {
            get {
                return ResourceManager.GetString("alreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Last Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string deleteBtn {
            get {
                return ResourceManager.GetString("deleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this tweet? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string deleteComfirm {
            get {
                return ResourceManager.GetString("deleteComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete has been cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string deleteNo {
            get {
                return ResourceManager.GetString("deleteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet has been deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string deleteYes {
            get {
                return ResourceManager.GetString("deleteYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer&apos;s Twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeveloperTwitter {
            get {
                return ResourceManager.GetString("DeveloperTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status is a duplicate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string helpMenuTitle {
            get {
                return ResourceManager.GetString("helpMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An internet is not available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string networkNotAvailable {
            get {
                return ResourceManager.GetString("networkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OAuth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OAuth {
            get {
                return ResourceManager.GetString("OAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Repository に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectRepository {
            get {
                return ResourceManager.GetString("ProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sendBtn {
            get {
                return ResourceManager.GetString("sendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string settingsMenuTitle {
            get {
                return ResourceManager.GetString("settingsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string showProfileMenuItem {
            get {
                return ResourceManager.GetString("showProfileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tooLong {
            get {
                return ResourceManager.GetString("tooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet is too short. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tooShort {
            get {
                return ResourceManager.GetString("tooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top Most に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string topMostMenuItem {
            get {
                return ResourceManager.GetString("topMostMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter Exception! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TwitterException {
            get {
                return ResourceManager.GetString("TwitterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown Exception! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Word Wrap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string wordWrapMenuItem {
            get {
                return ResourceManager.GetString("wordWrapMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no account. Please add a twitter account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string yetAdded1 {
            get {
                return ResourceManager.GetString("yetAdded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application will exit if you select No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string yetAdded2 {
            get {
                return ResourceManager.GetString("yetAdded2", resourceCulture);
            }
        }
    }
}
